//console.log(process);
//process 和 global.process是同一个对象
console.log(global.process==process);//true
//process.argv 属性返回一个数组，其中包含当启动 Node.js 进程时传入的命令行参数
console.log(process.argv);
//process.env 属性返回包含用户环境的对象
		//console.log(process.env);
//process.pid 属性返回进程的PID。
console.log(process.pid);
console.log(1);
//process.nextTick(callback) 方法将 callback 添加到下一个时间点的队列
process.nextTick(()=>{
	console.log(2)
})
console.log(3);
/*
process {
  title: ' ',
  version: 'v10.15.3',
  versions:
   { http_parser: '2.8.0',
     node: '10.15.3',
     v8: '6.8.275.32-node.51',
     uv: '1.23.2',
     zlib: '1.2.11',
     ares: '1.15.0',
     modules: '64',
     nghttp2: '1.34.0',
     napi: '3',
     openssl: '1.1.0j',
     icu: '62.1',
     unicode: '11.0',
     cldr: '33.1',
     tz: '2018e' },
  arch: 'x64',
  platform: 'win32',
  release:
   { name: 'node',
     lts: 'Dubnium',
     sourceUrl:
      'https://nodejs.org/download/release/v10.15.3/node-v10.15.3.tar.gz',
     headersUrl:
      'https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz',
     libUrl:
      'https://nodejs.org/download/release/v10.15.3/win-x64/node.lib' },
  argv:
   [ 'C:\\Program Files\\nodejs\\node.exe',
     'D:\\liyu\\wl2018\\11-node.js\\03-global\\process.js' ],
  execArgv: [],
  env:
   { ACLOCAL_PATH: '/mingw64/share/aclocal:/usr/share/aclocal',
     ALLUSERSPROFILE: 'C:\\ProgramData',
     APPDATA: 'C:\\Users\\94ish\\AppData\\Roaming',
     COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files',
     'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
     CommonProgramW6432: 'C:\\Program Files\\Common Files',
     COMPUTERNAME: '94ISH-20190317Y',
     COMSPEC: 'C:\\WINDOWS\\system32\\cmd.exe',
     CONFIG_SITE: '/mingw64/etc/config.site',
     DISPLAY: 'needs-to-be-defined',
     EXEPATH: 'C:\\Program Files\\Git',
     FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
     FPS_BROWSER_USER_PROFILE_STRING: 'Default',
     HOME: 'C:\\Users\\94ish',
     HOMEDRIVE: 'C:',
     HOMEPATH: '\\Users\\94ish',
     HOSTNAME: '94ISH-20190317Y',
     INFOPATH: '/usr/local/info:/usr/share/info:/usr/info:/share/info',
     LANG: 'zh_CN.UTF-8',
     LOCALAPPDATA: 'C:\\Users\\94ish\\AppData\\Local',
     LOGONSERVER: '\\\\94ISH-20190317Y',
     MANPATH:
      '/mingw64/local/man:/mingw64/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man',
     MINGW_CHOST: 'x86_64-w64-mingw32',
     MINGW_PACKAGE_PREFIX: 'mingw-w64-x86_64',
     MINGW_PREFIX: '/mingw64',
     MSYSTEM: 'MINGW64',
     MSYSTEM_CARCH: 'x86_64',
     MSYSTEM_CHOST: 'x86_64-w64-mingw32',
     MSYSTEM_PREFIX: '/mingw64',
     NUMBER_OF_PROCESSORS: '4',
     OLDPWD: '/d/liyu/wl2018/11-node.js',
     OneDrive: 'C:\\Users\\94ish\\OneDrive',
     ORIGINAL_PATH:
      'C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\94ish\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WI
NDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs;C:\\Users\\94ish
\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\94ish\\AppData\\Roaming\\npm',
     ORIGINAL_TEMP: '/tmp',
     ORIGINAL_TMP: '/tmp',
     OS: 'Windows_NT',
     PATH:
      'C:\\Users\\94ish\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;
C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\94ish\\bin;C:\\WINDOWS\\s
ystem32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\Git\\cmd;C:\\Program File
s\\nodejs;C:\\Users\\94ish\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\94ish\\AppData\\Roaming\\npm;C:\\Program Files\\Git\\usr\\bin
\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl',
     PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
     PKG_CONFIG_PATH: '/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig',
     PLINK_PROTOCOL: 'ssh',
     PROCESSOR_ARCHITECTURE: 'AMD64',
     PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
     PROCESSOR_LEVEL: '6',
     PROCESSOR_REVISION: '3c03',
     ProgramData: 'C:\\ProgramData',
     PROGRAMFILES: 'C:\\Program Files',
     'ProgramFiles(x86)': 'C:\\Program Files (x86)',
     ProgramW6432: 'C:\\Program Files',
     PS1:
      '\\[\\033]0;$TITLEPREFIX:$PWD\\007\\]\\n\\[\\033[32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps1`\\
[\\033[0m\\]\\n$ ',
     PSModulePath:
      'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
     PUBLIC: 'C:\\Users\\Public',
     PWD: '/d/liyu/wl2018/11-node.js/03-global',
     SESSIONNAME: 'Console',
     SHELL: 'C:\\Program Files\\Git\\usr\\bin\\bash.exe',
     SHLVL: '1',
     SSH_ASKPASS: '/mingw64/libexec/git-core/git-gui--askpass',
     SYSTEMDRIVE: 'C:',
     SYSTEMROOT: 'C:\\WINDOWS',
     TEMP: 'C:\\Users\\94ish\\AppData\\Local\\Temp',
     TMP: 'C:\\Users\\94ish\\AppData\\Local\\Temp',
     TMPDIR: 'C:\\Users\\94ish\\AppData\\Local\\Temp',
     USERDOMAIN: '94ISH-20190317Y',
     USERDOMAIN_ROAMINGPROFILE: '94ISH-20190317Y',
     USERNAME: '94ish',
     USERPROFILE: 'C:\\Users\\94ish',
     WINDIR: 'C:\\WINDOWS',
     _: '/usr/bin/winpty' },
  pid: 6080,
  features:
   { debug: false,
     uv: true,
     ipv6: true,
     tls_alpn: true,
     tls_sni: true,
     tls_ocsp: true,
     tls: true },
  ppid: 4452,
  execPath: 'C:\\Program Files\\nodejs\\node.exe',
  debugPort: 9229,
  _debugProcess: [Function: _debugProcess],
  _debugEnd: [Function: _debugEnd],
  _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
  _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
  abort: [Function: abort],
  chdir: [Function: chdir],
  umask: [Function: umask],
  _getActiveRequests: [Function: _getActiveRequests],
  _getActiveHandles: [Function: _getActiveHandles],
  _kill: [Function: _kill],
  cwd: [Function: cwd],
  dlopen: [Function: dlopen],
  reallyExit: [Function: reallyExit],
  uptime: [Function: uptime],
  _rawDebug: [Function],
  moduleLoadList:
   [ 'Internal Binding module_wrap',
     'Binding contextify',
     'Internal Binding worker',
     'NativeModule events',
     'NativeModule internal/async_hooks',
     'NativeModule internal/errors',
     'Binding uv',
     'Binding buffer',
     'Binding async_wrap',
     'Internal Binding async_wrap',
     'Binding config',
     'Binding icu',
     'NativeModule util',
     'NativeModule internal/util/inspect',
     'Binding util',
     'NativeModule internal/util',
     'Binding constants',
     'Internal Binding types',
     'NativeModule internal/util/types',
     'NativeModule internal/validators',
     'NativeModule internal/encoding',
     'Internal Binding icu',
     'NativeModule buffer',
     'NativeModule internal/buffer',
     'NativeModule internal/process/per_thread',
     'NativeModule internal/process/main_thread_only',
     'NativeModule internal/process/stdio',
     'NativeModule assert',
     'NativeModule internal/assert',
     'NativeModule fs',
     'NativeModule path',
     'NativeModule internal/constants',
     'Binding fs',
     'NativeModule internal/fs/streams',
     'NativeModule internal/fs/utils',
     'NativeModule stream',
     'NativeModule internal/streams/pipeline',
     'NativeModule internal/streams/end-of-stream',
     'NativeModule internal/streams/legacy',
     'NativeModule _stream_readable',
     'NativeModule internal/streams/buffer_list',
     'NativeModule internal/streams/destroy',
     'NativeModule internal/streams/state',
     'NativeModule _stream_writable',
     'NativeModule _stream_duplex',
     'NativeModule _stream_transform',
     'NativeModule _stream_passthrough',
     'NativeModule internal/url',
     'NativeModule internal/querystring',
     'Binding url',
     'NativeModule internal/process/warning',
     'NativeModule internal/process/next_tick',
     'NativeModule internal/process/promises',
     'Internal Binding util',
     'NativeModule internal/fixed_queue',
     'Binding performance',
     'Binding trace_events',
     'NativeModule internal/inspector_async_hook',
     'Binding inspector',
     'NativeModule internal/options',
     'Internal Binding options',
     'NativeModule timers',
     'Binding timer_wrap',
     'NativeModule internal/linkedlist',
     'NativeModule internal/timers',
     'NativeModule console',
     'Binding tty_wrap',
     'Internal Binding tty_wrap',
     'NativeModule tty',
     'NativeModule net',
     'NativeModule internal/net',
     'Binding stream_wrap',
     'Binding tcp_wrap',
     'Binding pipe_wrap',
     'NativeModule internal/stream_base_commons',
     'Internal Binding stream_wrap',
     'Internal Binding uv',
     'NativeModule internal/tty',
     'Binding signal_wrap',
     'NativeModule internal/modules/cjs/loader',
     'NativeModule vm',
     'NativeModule url',
     'NativeModule internal/safe_globals',
     'NativeModule internal/modules/cjs/helpers',
     'NativeModule os',
     'Binding os' ],
  binding: [Function: binding],
  _linkedBinding: [Function: _linkedBinding],
  _events:
   [Object: null prototype] {
     newListener: [Function],
     removeListener: [Function],
     warning: [Function],
     SIGWINCH: [ [Function], [Function] ] },
  _eventsCount: 4,
  _maxListeners: undefined,
  _fatalException: [Function],
  domain: null,
  _exiting: false,
  assert: [Function: deprecated],
  config:
   { target_defaults:
      { cflags: [],
        default_configuration: 'Release',
        defines: [],
        include_dirs: [],
        libraries: [] },
     variables:
      { asan: 0,
        build_v8_with_gn: false,
        coverage: false,
        debug_nghttp2: false,
        enable_lto: false,
        enable_pgo_generate: false,
        enable_pgo_use: false,
        force_dynamic_crt: 0,
        host_arch: 'x64',
        icu_data_in: '..\\..\\deps/icu-small\\source/data/in\\icudt62l.dat',
        icu_endianness: 'l',
        icu_gyp_path: 'tools/icu/icu-generic.gyp',
        icu_locales: 'en,root',
        icu_path: 'deps/icu-small',
        icu_small: true,
        icu_ver_major: '62',
        nasm_version: '2.14',
        node_byteorder: 'little',
        node_debug_lib: false,
        node_enable_d8: false,
        node_enable_v8_vtunejit: false,
        node_install_npm: true,
        node_module_version: 64,
        node_no_browser_globals: false,
        node_prefix: '/usr/local',
        node_release_urlbase: 'https://nodejs.org/download/release/',
        node_shared: false,
        node_shared_cares: false,
        node_shared_http_parser: false,
        node_shared_libuv: false,
        node_shared_nghttp2: false,
        node_shared_openssl: false,
        node_shared_zlib: false,
        node_tag: '',
        node_target_type: 'executable',
        node_use_bundled_v8: true,
        node_use_dtrace: false,
        node_use_etw: true,
        node_use_large_pages: false,
        node_use_openssl: true,
        node_use_pch: false,
        node_use_perfctr: true,
        node_use_v8_platform: true,
        node_with_ltcg: true,
        node_without_node_options: false,
        openssl_fips: '',
        openssl_no_asm: 0,
        shlib_suffix: 'so.64',
        target_arch: 'x64',
        v8_enable_gdbjit: 0,
        v8_enable_i18n_support: 1,
        v8_enable_inspector: 1,
        v8_no_strict_aliasing: 1,
        v8_optimized_debug: 0,
        v8_promise_internal_field_count: 1,
        v8_random_seed: 0,
        v8_trace_maps: 0,
        v8_typed_array_max_size_in_heap: 0,
        v8_use_snapshot: true,
        want_separate_host_toolset: 0 } },
  setUncaughtExceptionCaptureCallback: [Function],
  hasUncaughtExceptionCaptureCallback: [Function],
  emitWarning: [Function],
  nextTick: [Function: nextTick],
  _tickCallback: [Function: _tickCallback],
  stdout: [Getter],
  stderr: [Getter],
  stdin: [Getter],
  openStdin: [Function],
  hrtime: { [Function: hrtime] bigint: [Function] },
  cpuUsage: [Function: cpuUsage],
  memoryUsage: [Function: memoryUsage],
  exit: [Function],
  kill: [Function],
  argv0: 'C:/Program Files/nodejs/node.exe',
  allowedNodeEnvironmentFlags: [Getter/Setter],
  mainModule:
   Module {
     id: '.',
     exports: {},
     parent: null,
     filename: 'D:\\liyu\\wl2018\\11-node.js\\03-global\\process.js',
     loaded: false,
     children: [],
     paths:
      [ 'D:\\liyu\\wl2018\\11-node.js\\03-global\\node_modules',
        'D:\\liyu\\wl2018\\11-node.js\\node_modules',
        'D:\\liyu\\wl2018\\node_modules',
        'D:\\liyu\\node_modules',
        'D:\\node_modules' ] } }

 */